### ISSUE TITLE
UA "NetFront" and "NX" gets incorrect score

### ISSUE THREAD

**Issue by dayninth** [WebPlatformTest/HTML5test#136]
As you might know, NetFront Browser has been deployed over 1 billion embedded devices, and it's been shipped in numerous Pay TV STBs, Connected TVs and mobile phones world-wide. More detail can be found below:

http://www.access-company.com/news/press/ACCESS/2011/20110214a_nf1b.html

I am keen on the approach taken in html5test.com, but today I see some issues.

We have our Browser NetFront NX from ACCESS, and I ran the html5 testing with it today. I found the odd things happened.

If I specify the UA string as null, I get good score: 358
If I use the proper UA string either "NetFront" or "NX", which seem to have been registered in the website, I get much lower score: 324

It's exactly the same Browser, and the only difference is the setting of UA. I found the difference comes from the testing "User interaction": the former setting gets 35 points while the latter gets only 1.

Could you please help me out as soon as practical? 

Thanks in advance!

**Comment by NielsLeenheer** [comment]
Hi, I was hoping to get into contact with somebody from Access, especially because of this issue.

We found that a lot of non-desktop browsers do not have proper support for contentEditable and HTML5 drag and drop. In many cases these browsers do report that they support these features, leading to false positive. To prevent this we've added a whitelist for each of these features. If you are not on this whitelist (and NetFront is not currently) you cannot get points for these two features. 

The reason you get more points with an null UA strings, is because that UA isn't recognized, it is classified as 'desktop' which does not use the whitelist.

I'd love to add NetFront to these whitelists, but I do need confirmation on the following questions:

a) Does NetFront support contentEditable?
b) If so, since which version?

You can test contentEditable on the following website: http://html5demos.com/contenteditable
Please make sure you can actually change the text. Some browsers do allow text selection, but never pop up a keyboard.

c) Does NetFront support HTML5 drag and drop?
d) If so, since which version?

You can test drag and drop on the following website: http://html5demos.com/drag

Cheers,

Niels

**Comment by ghost** [comment]
Hi, I'm Kosuke Nagano from ACCESS. 
gmkou is my private account. Thank you for accept my pull-request. :)

I'd like to order you to fix our score. Currently, NetFrontNX v2.1 getting score 399. But it's strange, we can't reproduce that score by our side even if we use development version. So, please downgrade our score to 334. Maybe you have log right now.

And I'll reply you instead of dayninth.
a) Does NetFront support contentEditable?
NetFront NX doesn't support contentEditable right now. We'd like to implement it but not scheduled.

c) Does NetFront support HTML5 drag and drop?
NetFront NX doesn't support contentEditable right now. We'd like to implement it but not scheduled and it needs many trick to enable this feature on embedded system because many of that doesn't have "desktop".

regards,
Kosuke.
