### ISSUE TITLE
Show Minibrowser Mobile 4.0 for S60 in browser comparison

### ISSUE THREAD

**Issue by Vish123** [WebPlatformTest/HTML5test#138]
When i go to the site using this browser, i get 280 + 13 bonus points. i reckon it is worth putting this result up in the mobile phone comparison. though one problem is that the site detected the browser as "Minibrowser 4.0 on windows 7", even though this is on my phone. Another browser you can add is maxthon for android. you have already included the desktop version so it should be alright to put up the results for the mobile version.

**Comment by NielsLeenheer** [comment]
At this time I will not add Maxthon for Android because it scores ate comparable with the default browser. Probably because they both use the stock rendering engine.

Regarding Minibrowser Mobile: could you is it html5test.com and mention the Test ID in this bug? You can find the ID just below the test results.
