### ISSUE TITLE
micro data:HTMLPropertiesCollection hasn't name property.

### ISSUE THREAD

**Issue by wesleyzeng** [WebPlatformTest/HTML5test#139]
engine.js:

M = M && !!("properties" in N) && N.properties.name[0].itemValue == "Elizabeth";
......

M = M && K.properties.name[0].itemValue == "Elizabeth"
......

According to http://www.w3.org/TR/microdata/#htmlpropertiescollection, HTMLPropertiesCollection hasn't name property.

**Comment by NielsLeenheer** [comment]
If you look at the source code here on Github, you'll notice it is written as properties['name'] instead of properties.name. Name isn't a property of the HTMLPropertiesCollection object, but shorthand for namedItem(). 

The reason it is different on the site and here on Github is because the code on the site is minified. It shouldn't matter, because both mean exactly the same, it is just a different notation.
