### ISSUE TITLE
Why Maxthon browser to force display does not support html5 date input?

### ISSUE THREAD

**Issue by wesleyzeng** [WebPlatformTest/HTML5test#152]
The details as follow:

engine.js: 

var Q = Browsers.isBrowser("Maxthon"); 

// If it is maxthon browser, passed is equal to false.
S.setItem({id: "ui",passed: !Q && ai && (aa.field != C(L.field) || aa.wrapper != C(L.wrapper)),value: 2});

**Comment by NielsLeenheer** [comment]
I've created a blacklist for "Custom UI" detection. The implementation by Maxthon is simply not good enough. Instead of a date or time picker there is just a couple of spin buttons. Until there is a better implementation Maxthon will no longer score points for "Custom UI" on all date related input fields and the color input field.

**Comment by wesleyzeng** [comment]
Thank you very much. However, the effect of the safari window version and maxthon support date picker is the same.

**Comment by NielsLeenheer** [comment]
True. Safari does not get any points for "Custom UI" either. They are not on the blacklist because their implementation does not trigger the test like Maxthon does.
