### ISSUE TITLE
Firefox Nighly

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#158]
Firefox Nightly should be present on the list of upcoming browsers. It gets 393 HTML5 Points and 10 bonus points.
Version - 19.0a1(2012-10-15).

**Comment by PhoneixS** [comment]
I also think that the list of browsers must be updated so it include Firefox betas and the last stable Firefox.

**Comment by Form32** [comment]
Firefox Nightly 18.0a1 (2012-09-01) now scores 389 points and 9 bonus points

**Comment by Caspy7** [comment]
Firefox development version include Nightly, Aurora and Beta, but none of them are listed under "Development or Beta".  They are very easy to obtain and test.  This issue was opened almost a year ago so I can only wonder if this is being done to intentionally skew perceptions.
Is no data being gathered from the test?  I know that there are multiple users testing with pre-release versions of Firefox, simply grabbing the mode should not be difficult.

**Comment by fbender** [comment]
@NielsLeenheer, how do you deal with changing scores within a version? Per the nature of Firefox Nightly, the score of each version can change significantly within the six-week development period. If you only intend to collect this data once, then I'd rather advise you to use Firefox Aurora as the "upcoming" version. Scores may still change within the Aurora period (e.g. due to enabling or disabling of features) though the numbers are less in flux.

**Comment by NielsLeenheer** [comment]
Nightly browsers are updated too often include. After the launch of the new version, I'll try to keep track of Firefox Aurora.
