### ISSUE TITLE
Filesystem API is Chrome-proprietary, not a future W3C standard

### ISSUE THREAD

**Issue by bzbarsky** [WebPlatformTest/HTML5test#167]
It's a bit confusing because the bar for introducing a working draft at the W3C is so low, but the Filesystem API is basically a Chrome-proprietary feature that no one else is planning to implement and that is not advancing on the standards track.

It would probably be better to not test for it in a test that talks about "all major browser manufacturers" and so forth and is meant to test things that are likely to actually become standards.

**Comment by NielsLeenheer** [comment]
On the Webapps WG PubStatus wiki page it is stil listed among the specifications that are in active development: http://www.w3.org/2008/webapps/wiki/PubStatus. Also it seems there is some progress, because the working draft has been updated April 17th of this year. 

Also some other vendors are shipping or going to ship implementations such as BlackBerry, Netfront and Tizen.
http://html5test.com/compare/feature/files-fileSystem.html

Are you saying Mozilla (and perhaps others) has no intention to implement this at this time, or that it is basically a dead proposal that will never move forward on the standards track.

**Comment by bzbarsky** [comment]
On 7/10/12 9:35 AM, Niels Leenheer wrote:

> On the Webapps WG PubStatus wiki page it is stil listed among the specifications that are in active development: http://www.w3.org/2008/webapps/wiki/PubStatus. Also it seems there is some progress, because the working draft has been updated April 17th of this year.
> 
> Also some other vendors are shipping or going to ship implementations such as BlackBerry, Netfront and Tizen.
> http://html5test.com/compare/feature/files-fileSystem.html
> 
> Are you saying Mozilla (and perhaps others) has no intention to implement this at this time, or that it is basically a dead proposal that will never move forward on the standards track.

As far as I know, Mozilla, Apple, Opera, and Microsoft have all stated 
that they have no intention of implementing this proposal.

If that doesn't change, it will fail to move forward due to lack of 
independent interoperable implementations, as far as I can tell...

-Boris

**Comment by BrendanEich** [comment]
http://lists.w3.org/Archives/Public/public-webapps/2012JulSep/0820.html

/be

**Comment by miketaylr** [comment]
objections from Opera: http://lists.w3.org/Archives/Public/public-webapps/2012JulSep/0801.html

**Comment by NielsLeenheer** [comment]
The next version of html5test.com will still test for the Filesystem API, but will award no points for supporting it.
