### ISSUE TITLE
wrong html5 test result with the new maxthon 4.0.3

### ISSUE THREAD

**Issue by Mirr0ch1** [WebPlatformTest/HTML5test#229]
the maxthon 4.0.3 (a beta version) has been pushed from the official homepage. Anyway the html5test didn't list it in the browsers compare page. Although it could detected I was using Maxthon 4 on win8, the test score would be the same as maxthon 3.4. But if I changed the user agent setting (like changed it into the IE6 IE7 Safari). The score would be 469!
![ 1](https://f.cloud.github.com/assets/3250823/61838/74bb2a72-5c98-11e2-826e-d64149bd4129.png)
![ ](https://f.cloud.github.com/assets/3250823/61839/74bfc87a-5c98-11e2-9cd5-03a0ae3231c9.png)

**Comment by NielsLeenheer** [comment]
Some features of Maxthon were on a blacklist because they did not actually work. With version 4 most of these issues have been solved and I expect that with 4.0.5 all remaining issues are fixed. I still need to confirm this, but if so I will update the blacklists and Maxthon should be able to get the score you mentioned.

**Comment by NielsLeenheer** [comment]
Maxthon has been removed from the blacklist.
