### ISSUE TITLE
Malicious usage of "http://html5test.com/scripts/useragents.php"

### ISSUE THREAD

**Issue by LittleShadow** [WebPlatformTest/HTML5test#230]
Hi,
Just find the file of http://html5test.com/scripts/useragents.php has been maliciously used by some other sites to detect the user agent.

It gets embedded into other sites in this way:
&lt;script type="text/javascript" src="http://html5test.com/scripts/useragents.php" &gt; &lt;/script>

followed by lines like these:
var ua = new UserAgents();
var browser_name = ua.browser.name;

This may leads to unexpected traffic to your server. I'd suggest you to make the detection code as a static js file which can be copied and embedded in any html file.

**Comment by JohnBear** [comment]
Wow... it may be possible. Please take care of this.

**Comment by NielsLeenheer** [comment]
I'm not seeing big problems with the server, so it does not have a big impact, but this is certainly not a public API. I've already contacted a Chinese blogger who posted a script using useragent.php and he graciously removed it. 

Moving to a static js file is not possible, because the device model database has grown too large. I moved specifically to server side detection to make loading html5test faster. The port to PHP is now quite stable, so I'll release the source code soon, so others can simply use their own useragent.php instead of linking to html5test.

Do you have any examples of other websites that use this script?

**Comment by LittleShadow** [comment]
Would you consider take the hot link protection? That could prevent the potential server stress.

**Comment by NielsLeenheer** [comment]
Changed the location, so all current users are receiving 404s. Also the code is now public, so if others want to use it, they are welcome. Provided they use their own server.
