### ISSUE TITLE
canvas "2D context" test tests for particular object stringification behavior

### ISSUE THREAD

**Issue by dbaron** [WebPlatformTest/HTML5test#24]
The canvas "2D context" test tests for particular behavior when converting objects to strings in the following code:

```
                var r = this.canvas.getContext && this.canvas.getContext('2d') == '[object CanvasRenderingContext2D]';
```

This unnecessarily fails on Gecko-based browsers, which provide additional information when converting objects to strings, even though canvas 2D context is supported.

A simple equivalent to the current test that is more portable would be:

```
                var r = this.canvas.getContext && this.canvas.getContext('2d') instanceof CanvasRenderingContext2D;
```

**Comment by dbaron** [comment]
The same problem also occurs in some other tests that Gecko should pass, such as that for the keygen element, as well as a number that I wouldn't expect it to pass.

**Comment by NielsLeenheer** [comment]
I don't see any problems with using toString() to test for the type of an object in Gecko. In fact in all versions of Mozilla Firefox I tested, the 2d context is detected without any problems.

instanceof does need an additional check. Otherwise it will throw an error if you check for an object type that is not defined yet. For example a browser that has not implemented canvas will throw an error in your example.

You could solve that with something like this:

  typeof HTMLKeygenElement == 'object' && document.createElement('keygen') instanceof HTMLKeygenElement

Can you give me an example of why toString() fails in Gecko and which browsers are affected?

**Comment by dbaron** [comment]
Hmmm.  Maybe it's only different in debug builds of Gecko, but I see:
[object CanvasRenderingContext2D @ 0x7f9db75436c0 (native @ 0x7f9d9d076280)]

That said, this is also a bad way of testing things because it's not future-compatible.  For example, if many of the elements that you test are exactly [object HTMLElement] in the future have their own DOM interfaces, then they won't be [object HTMLElement] anymore.  And it seems like a bad idea to have a test for standards support discourage future innovation (and also demonstrate a bad technique for testing).  instanceof is much more future-proof that way since it's checking what interfaces are supported rather than a concrete (most-derived) type.

**Comment by NielsLeenheer** [comment]
I think it is indeed restricted to debug builds. But nevertheless, it is a prefect example of why toString() is not reliable.
