### ISSUE TITLE
Android browsers supports the coded,  test return wrong result 

### ISSUE THREAD

**Issue by pratiknvyas** [WebPlatformTest/HTML5test#248]
Hi ,
I appreciate your effort for developing such a nice script.
I find issue with android browser, android browser dose support MP4 as well as webM but HTML5 test provide wrong result.

**Comment by silasoverturf** [comment]
What android browser are you using? Not sure how the MP4 support is, but webM checks out fine on Chrome.

**Comment by NielsLeenheer** [comment]
Part of supporting a codec, is also properly support detecting those codecs. 

If some web developer writes a script that asks the browser which codecs it supports and the browser does not give me accurate results how should he know which codecs are supported. The script will just use the codec the browser does say it supports. Might as well not support those other codecs at all, because they are never used.

I'm not sure about this particular case, but I do know that the stock Android browser has notoriously bad support for canPlayType() and does not follow the rules laid out in the HTML5 specification. HTML5test.com just reports what the browser tells us about which codecs it supports. If HTML5test is wrong, the browser gave us the wrong results.

**Comment by pratiknvyas** [comment]
Hi Silasoverturf,
I was using default browser of the Android mobile
