### ISSUE TITLE
Yandex Browser

### ISSUE THREAD

**Issue by boiler23** [WebPlatformTest/HTML5test#341]
Hi,

May you please add Yandex Browser to the list? It scores 501 points and works on desktop, tablet & mobile. It is the fifth largest browser in Russian Internet with market share about 6-7%.
http://html5te.st/8601ad208b7c8bd8

Thanks!

**Comment by ron-wolf** [comment]
Yandex Browser is based on Chromium and its Blink engine, itself a heavily customized WebKit. It also uses Opera's webpage caching features, in addition to Kaspersky's security features. In short, it's Yandex's effort to compete with Google Chrome, minus the open-source part, because that would make the copying even more obvious. As per the "Reporting" section [here](http://html5test.com/about.html), Yandex Browser isn't eligible. Any differences in score are likely due to features being blocked by Kaspersky, though they might also be a bit behind on the Chromium update schedule.

**Comment by boiler23** [comment]
Yandex Browser is based on Chromium and Blink, that's right. But you are wrong in thinking it is just a copy of Google Chrome. Browser UI is original and engine also has major modifications, not of them being upstreamed to Blink.
Also you are completely wrong about differences in score. Kaspersky security check is only done for downloaded files, it has no influence on web features. Differences may be because of some features not yet ready in Yandex Browser or they may be disabled, as well as they may be disabled or not yet ready in Chromium, but already shipping within Yandex Browser. I think this may be useful for web developers.
Opera browser is also based on Chromium/Blink and it is present in the list. Why not add Yandex?

**Comment by ron-wolf** [comment]
Well, obviously the UI is original; otherwise, it would be a direct copy!

Being able to block downloads requires injecting code, which may require/disable certain features such as iframes. I highly doubt Kaspersky bothered developing a proxy for that kind of thing, as they haven’t exactly been known to go the extra mile for their users, in fact going a mile or two backward in some cases (_cough_ _cough_ crapware _cough_).

If a feature is shipped but not activated, it may as well still be in the works or not exist at all as far as the user is concerned. Also, how is disabling features available in Chromium itself useful to devs? They can already disable whatever they want using API tools, and other features are available as modifiable flags accessible via the UI. This may be useful in some cases, but I don’t think most people would benefit from features disabled by default. Let me know the next time you meet someone who develops explicitly for Yandex Browser. People develop for engines, not browsers, especially not ones like Yandex Browser, because most of the Internet market is in the West, western Europe, and the Far East—Japan, specifically. I’m pretty sure Yandex didn’t modify Blink as heavily as you think, and anyway Opera used a completely different engine, making it worth it until then to develop for that separately, until 2012, by which point this site had already added it. Opera was based on Blink just as Blink is based on WebKit. Until they change the name of their engine, it’s pretty much considered the same engine with a few features given and taken. You just can’t put Yandex Browser on the list of browsers whose devs have put a ton of effort into making unique and useful. It’s a one-hit wonder that’s bundled with a search engine. Google tried that with Google Toolbar, which did not go too well, only fooling some overly adventurous kids like I was.

I’m not saying it’s exactly the same as Chrome, because that wouldn’t make any sense whatsoever. I’m saying it’s a knockoff: a half-baked answer to a much more experienced and well-organized company’s effort to expand the web. Yandex just doesn’t have the same resources as Google! I’m sure they’re very popular in and around their home country, but with the Internet you have to take the full picture into account, and I’m not too confident in what the full picture has to say about Yandex Browser.

Sorry if it sounds like I’m insulting your opinion or anything—that’s not what I intend. I just don’t think Yandex Browser has the stuff to warrant tracking all its features separately from Chrome’s.

**Comment by boiler23** [comment]
Wow, I'm really impressed with your vision of Yandex and its products. Especially it looks very interesting for me, how did you manage to know much about its experience and organization. Didn’t you ever work for them btw? Anyway, I cannot agree with you.

First. Ability to block downloads is a part of safe-browsing engine, which is a standard mechanism in most browsers (Chrome as well). Yandex uses its own safe-browsing database and Kaspersky provides a subset of it. Your opinion about Kaspersky’s own products quality is completely out of place here.

Second. Features may or may not be ready for broad distribution (enabled by default) in Yandex or Chrome at particular moments because of different workflow, release cycles and approaches for development in both companies. You are right, most of the internet market is in US (and in China as well, huh), but Russian internet market is the largest one in Europe and many web dev’s here take Yandex Browser in account. Moreover, many of them use html5test.com as an instrument to compare browser features they can rely on.

Third. Yandex uses Blink in exactly the same way as Opera does. Both companies intake fresh Chromium on regular basis. Both companies make contributions to Blink and have a proprietary part. I don’t get where is the difference here.

Forth. Comparing Yandex Browser and Google Toolbar is totally inappropriate - these products are completely different in their purposes, audiences and features. The one and only goal for toolbar product is search distribution. Yandex's browser is a product for people, it’s a company’s effort to make the web better and it’s vision on how a browser should look like. And it is definitely not a one-hit wonder as you think.

**Comment by ron-wolf** [comment]
Please spare me the obscure sarcasm, straw men, and rationalization.

I was hoping for this not to turn into an flame war, and if you analyze my other comment impartially you’ll see I went to great lengths to respect your opinions and preferences, so please do the same for me, regardless of how wrong you believe I am. There is no such thing as an "out-of-place" opinion, but there are mature and immature ways to present them. To be honest, the way you present yours makes me wonder which you have in mind, pushing the modern browser or helping a company expand its market. It also seems you have not acknowledged a few good points I made; whether there was intention is not for me to know.

Unfortunately, I don’t think anyone has anything to gain from this thread, though I’m sure the dev will come and give the final word as he sees fit, so I am leaving; responding to this comment would be fruitless. Feel free to keep enjoying Yandex Browser as you wish.

**Comment by JacquesMarais** [comment]
I also want to make a request for this browser please. I have used this browser for a long time now. Please could you add it?

**Comment by DanAtkinson** [comment]
:-1:

It's just built on top of the Blink layout engine, so I don't see any reason to merit its inclusion, especially given the reporting guidelines already quoted by @ron-wolf [here](https://github.com/NielsLeenheer/html5test/issues/341#issuecomment-49468888).

**Comment by NielsLeenheer** [comment]
I'm hesitant to add Yandex at this time, and probably never as a primary browser due to low muted global market share. But I am planning on adding a way to better handle a larger number of secondary browsers.

**Comment by ron-wolf** [comment]
Interesting. Are you considering something along the lines of nesting
secondary browsers under primary browsers / engines?

**Comment by NielsLeenheer** [comment]
I don't have the time to maintain Pale Moon as a separate browser on HTMLtest. But the browser itself and version updates will be accepted as a PR as long as it is frequently maintained. See https://github.com/WebPlatformTest/Data for more information.
