### ISSUE TITLE
Neutralize passing test values

### ISSUE THREAD

**Issue by KieranP** [WebPlatformTest/HTML5test#36]
Don't get me wrong, HTML5Test is pretty neat/great! And the latest (http://beta.html5test.com/) looks pretty great UI wise.

But the scores for the entire test seems very opinionated and grossly disproportionate to their effectiveness and desirability among developers. It short, the scores are wrong. e.g. why does Local devices rate just as high as audio? Audio is far more useful and widely needed.

It would be better if each passing test gave just one point, so that the test gives a 'features implemented' count as opposed to the 'personal preference' count it appears to be at the moment.

Or is there some logic behind the current scoring?

**Comment by NielsLeenheer** [comment]
There is some logic behind the current scoring, but I can't deny there is some personal preference in it. Unfortunately I think that the current way is the only reasonable way despite it being a bit arbitrary.

One of the goals of html5test.com is to give users an idea of how the implementation of HTML5 is progressing. To give the user something they can use to compare browsers.
If every test is just a single point the test will become less useful in my opinion, because a browser that implements all kinds of small features could get more points than a browser that would implement some huge features. For example video and audio are big deal for HTML5 and a browser that implements these should get more points than a browser that implements footer and header.

Currently the logic is as follows:
- Large features get 20 points,
- Medium features get 10 points,
- Small features get 5 points,
- Individual elements and attributes get 1 point.

What makes a feature large, medium or small depends on the effort needed to add this particular feature and the impact it will have on web developers and users. Of course, this is where my personal preference comes in, but I am open to suggestions if somebody feels I give some features too much or too few points.

**Comment by KieranP** [comment]
I don't suppose you could support both via a context change link? :-)

Anyway, still a great test and looking forward to seeing browsers get closer to the total mark.
