### ISSUE TITLE
why outdated browser still in list 

### ISSUE THREAD

**Issue by muhasturk** [WebPlatformTest/HTML5test#375]
Opera has released 26 stable version and it has 508 point default html5 score. 
Chrome has released 39 stable version and it has 512 point default html5 score.

Please up to date top list. 

![](https://downloader-ams2.disk.yandex.com.tr/rdisk/1e4f96baf34d016edcf473517495d317/mpfs/I_zuW95MwHzFWxJ8NN2ZA4St0BmkzY3E1kBsVsnupehW186DvZqRXIHzye7nBBl1AlZhXbwN9gzwv5sOjnqYUQ==?uid=0&filename=2014-11-28%2019-00-39%20HTML5test%20-%20How%20well%20does%20your%20browser%20support%20HTML5%3F.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&rtoken=f1a3301d80ecdd7e6c21e409cba2fe58&rtimestamp=5478aa61&force_default=no)

**Comment by luisalvarado** [comment]
I think that is automatic. After an X amount of "latest versions" for a specific browser have ran the html test and the clients have also clicked on the "Is this your browser" that appears on the top of the html test results, they will show on this list. I am guessing it has taking this long because not many have updated yet (Even after a month O.o ).

**Comment by NielsLeenheer** [comment]
A new version of the site has launched today, including newer scores.

**Comment by muhasturk** [comment]
Still outdated
