### ISSUE TITLE
Add Microsoft Edge browser

### ISSUE THREAD

**Issue by PlanetVaster** [WebPlatformTest/HTML5test#384]
Please add the project spartan browser for windows 10

**Comment by DanAtkinson** [comment]
From what I understand, Project Spartan uses the following user agent string.

```
"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0"
```

I'm not sure why it's identifying itself as Chrome. If I had to guess, it's piggybacking their name so that any servers that modify the response for IE users don't get them in Project Spartan.

Edit (2015-05-06): Microsoft [article](https://msdn.microsoft.com/en-us/library/hh869301%28v=vs.85%29.aspx) on UA changes.

**Comment by R3gi** [comment]
Well Chrome is probably the most widely used browser and therefore many websites are optimized for it. If some less-known browser identify itself as XYZ, the page would not work as expected (e.g. display "Your browser is not supported", even if "it is"), but if it identify itself as Chrome...well that's something different.
But Spartan wasn't released yet, so it's a bit premature to add it right now...

**Comment by NielsLeenheer** [comment]
Edge will be added as a major browser with the next content update. It will probably not get a column of its own on the overview page, but added as a successor of Internet Explorer.
