### ISSUE TITLE
Firefox doesn’t support @ping. HTML5Test reports that it does

### ISSUE THREAD

**Issue by dstorey** [WebPlatformTest/HTML5test#397]
RE: https://twitter.com/frankolivier/status/623657281503277056

Firefox ships with the ping attribute disabled by default. Needs to be enabled via browser.send_pings in about:flags.

Test passes as it just tests for the presence of the ping attribute, and Firefox reports true when it is disabled. 

Test case: http://jsfiddle.net/2sysopzy/4/ . Run with Fiddler and observe that there is no network traffic unless it is enabled.

CC @NielsLeenheer

**Comment by NielsLeenheer** [comment]
I would say this qualifies to be put on the blacklist. 

With the upcoming update I have two ways a feature on the blacklist can be shown in the results. One way is simply "No": this is for features that cannot be properly tested like ContentEditable and drag and drop. The other way is "Broken" for features that are testable, but when the browser simply does not have a proper implementation. This would for example be for navigator.geolocation that always returns 0,0 as coordinates or a getGamepads API that never actually returns any gamepads.

I am considering adding a third way: "Disabled", because there is actually a functional implementation even if it is disabled. On the other hand I think breaking feature detection is worse enough to say "Broken".

**Comment by NielsLeenheer** [comment]
Went with "Broken".
