### ISSUE TITLE
Codecs are not required by the HTML5 spec

### ISSUE THREAD

**Issue by NielsLeenheer** [WebPlatformTest/HTML5test#4]
I’m worried that you penalise points for browsers not supporting one codec vs. another and assume that all browsers must implement all codecs. Considering that the choice of codec _is not part of the HTML5 specification_ I find it erroneous for you to be scoring against it–it’s called “The HTML5 test” but it’s testing for things not in the spec. Listing what codecs a browser suports is helpful, but I do hope you decide to not use this for scoring.

/via Kroc Camen

**Comment by NielsLeenheer** [comment]
How to score the codec support is something I struggled with. You are absolutely right that the specification does not specify a required codec or even makes any recommendation regarding codecs at all. I also realize that codec support is quite a controversial issue at the moment with supporters of Ogg Theora on one side and H.264 supporters on the other.

That being said, if I were to test the functionality of the <img> element, I would penalize implementations that do not support commonly used image formats, despite that the specification doesn’t say anything about which format should be supported. If a browser does not support transparent PNGs it would definitely score fewer points than one that did support it.

The codec situation can not be directly compared to images. It’s a bit more subtle, because the decision to support just one codec isn’t a technical issue or something that simply hasn’t been implemented yet. Which codec to support is more or less a political choice.

What I did was make the first codec count more than the second. If it supports just one codec the browser will get 25 points. If it supports an additional codec it will get 5 extra points. That should give a good indication of how important supporting both codecs is compared to just one. Firefox will get 25 points for supporting Ogg Theora and Safari will get 25 points for supporting H.264. Both implementations are equal according to the test. Chrome will get 30 points however, because it supports both. That does seems fair to me because if you compare it to Safari it does offer the additional support of Ogg Theora. If you compare it to Firefox it does offer the additional support of H.264.

Just think of it as Chrome getting bonus points instead of Firefox or Safari getting penalized. To emphasize this, I am considering of letting the score run from 0 – 155, instead of 0 – 160. Despite supporting just one codec Firefox and Safari would be able to get the full score of 155 out of 155. Chrome would score a maximum of 160 out of 155 for going beyond the specification…

**Comment by atonse** [comment]
This was also my issue regarding the scoring, that you were counting codec support towards the overall score. 

But I like your response and design, it's pragmatic. Perhaps you could put a link to a note in that element because I'm sure others will have the same question on codec support being used in the score.

Apart from that, this is a great idea! Good job.

**Comment by eyelidlessness** [comment]
I think that the problems with even scoring specific codecs is as follows:
1. The codecs tested are completely arbitrary. Beyond the fact that codec choice was controversial, another reason that no codec was specified in HTML5 is that vendors might want to implement new codecs as they become available. For instance, if Google licenses VP8 in a way that all browsers can safely implement, it would likely eventually become a de facto standard; but you're not testing for VP8.
2. It's quite probably not legally feasible for some vendors to implement H.264. A web standard should not be expected to support components which can't be legally implemented by some vendors; the entire point of a standard is to guide vendors implementing that standard toward universal interoperability. So H.264 should not be considered at all.

While you mitigate some of the problems with the consideration of particular codecs by treating a second codec as "bonus" points, that really isn't obvious until a browser reaches 100% support for all the other features; until that point, bonus points contribute to a false perception that a browser better supports HTML5 than it really does.

Specific codec support simply should not be considered as contributing to a browser's support for HTML5, because it isn't part of HTML5. Support for _any_ codec should be considered (as this is required to properly support the `<video>` element), and anything beyond that is moot.
