### ISSUE TITLE
Do not award points for supporting experimental features

### ISSUE THREAD

**Issue by PaintNinja** [WebPlatformTest/HTML5test#407]
I believe that awarding points for features marked as "Experimental" is unfair because it encourages web browser developers to prioritise work on supporting features that are very likely to change and therefore they would need to spend a lot of effort updating their support for the new changes rather than working on improving or adding support for Proposal or Stable features which are unlikely to change much if at all.

Current things I've noticed that award points for "Experimental" features include: (from HTML5test beta as of September 2015)
- Speech recognition
- Speech synthesis
- Web animations API
- Service workers
- Beacon
- Fetch
- Readable streams
- Writable streams
- Custom elements
- Shadow DOM
- HTML imports

**Comment by Studio384** [comment]
Web Cryptography API is also experimental but awards points.

**Comment by dstorey** [comment]
Web Crypto is now stable, or at least multiple vendors have implemented it without prefix. MS Edge upgraded from the older API to the unprefixed newer syntax.

**Comment by NielsLeenheer** [comment]
I do not think awarding points for experimental features is unfair. If the specifications change, we can change the tests too. See for example Shadow DOM; recently it got a completely different API and the next release of HTML5test will accept both and award points. 

Awarding points for experimental features is a way to get browser vendors to take a serious look at that technology. It is a way of pushing the platform forward.

**Comment by dstorey** [comment]
@NielsLeenheer speaking of experimental features that changed, IE10+ perhaps should get points for Readable Streams, as there was an initial MS proposal that didn't get update from other vendors, than a different Streams API (which is tested for here) came later.

IE supports readable streams like such: https://msdn.microsoft.com/en-us/library/hh772330(v=vs.85).aspx  There was a spec at http://html5labs.interoperabilitybridges.com/streamsapi/

**Comment by PaintNinja** [comment]
@NielsLeenheer If that's the case, why award the same amount of points for experimental features than stable features that are likely more in widespread use? From a consumer's point of view, having a browser support features in widespread use is more important to me than having a browser that supports experimental features which are not yet widely adopted.

**Comment by NielsLeenheer** [comment]
@PaintNinja The features that you listed as experimental are just worth 38 points. That is way less than 10% of the total amount of points a browser can score. HTML5test isn't just about testing features that are in widespread use. In fact when I started this site over 5 years ago most of the features I tested weren't in widespread use. This site has always been about pushing implementation of standards forward. And even the most widespread feature now was an experimental feature at one time.

**Comment by Studio384** [comment]
@NielsLeenheer "See for example Shadow DOM; recently it got a completely different API and the next release of HTML5test will accept both and award points."

Why award point for both the actual spec and the outdated, non-standard? Giving points for the later isn't pushing implementation of standards.

**Comment by NielsLeenheer** [comment]
@Studio384 In time I will drop points for the old spec. But the new spec is still very new right now and there are no implementations.

**Comment by dstorey** [comment]
I think reducing points for prefixed implementations is a good way to push vendors to update to the latest spec. Most modern browsers (except Safari) implement new experimental features behind a flag until they're stable, so it will only affect older specs/implementations that really need updating. And it doesn't penalise browser vendors as much that now put features behind a flag (0 points) vs vendors that use prefixes and leave prefixed implementation without the standardised version for a long time (full points). Features left prefixed for a long time hurts other vendors if the feature/prefix is popular as they end up having to implement the new spec and the old prefixed webkit one for interop (Like Edge had to for multiple features). 

E.g. if getUserMedia was 10 or 13 points instead of 15 if you only had the prefixed one, gaining 5 (or 2 or whatever points you remove) extra points for updating syntax, adding the promises version and removing the prefix could encourage vendors to do so.

**Comment by NielsLeenheer** [comment]
Closing this bug. I'm not going to drop points for experimental features. Prefixes has changed. See bug #454.
