### ISSUE TITLE
Support for webkitdirectory

### ISSUE THREAD

**Issue by DanielHerr** [WebPlatformTest/HTML5test#492]
webkitdirectory should also be listed as the current way to access folders. https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitDirectory

**Comment by dstorey** [comment]
This is non-standard, so I don't believe it should be in the test (no other non-standard APIs are for obvious reasons). Further more, I believe all non-Webkit/blink browsers (specifically Edge and Firefox) had to implement it for interop reasons anyway, so adding it wouldn't have an impact.

**Comment by fbender** [comment]
This is related to #305. Here's a discussion on the confusing status of the various FileSystem API(s): w3c/filesystem-api#8

What has been implemented and is available in most major engines by now is the [File and Directory Entries API](https://wicg.github.io/entries-api/), which ultimately superseded the Directory Upload proposal from Microsoft. So from my PoV it makes sense to test for the Entries API, however no points should be allocated since it uses vendor-specific names and is thus poised to be superseded by a more comprehensive API (e.g. FileSystem API) and/or to be included (at least in parts) into the HTML spec. Whenever that happens.

**Comment by NielsLeenheer** [comment]
Decided not to add webkitdirectory, waiting for consensus between browsers.
