### ISSUE TITLE
Geolocation v2 Spec

### ISSUE THREAD

**Issue by pento** [WebPlatformTest/HTML5test#52]
Geolocation v2 is currently in editor's draft:
http://dev.w3.org/geo/api/spec-source-v2.html

Firefox has implemented it, Webkit hasn't, not sure about the others. Perhaps it's worth including as bonus points, until it becomes a working draft?

**Comment by paulirish** [comment]
```
The Geolocation API Level 2 enhances the Geolocation API by adding support for civic addresses.
```

What's a civic address?

**Comment by pento** [comment]
Street address.

555 Some Street,
Town, State, zip
Country

**Comment by NielsLeenheer** [comment]
I'd love to do this, but I don't think this is possible without having to do an actual geolocation request and look at the results. And even then it is not reliable, because the browser may not know the civic address and only report the coordinates. 

The only thing I could find is a check like this:
typeof GeoPositionAddress != 'undefined'

However it looks like this is Mozilla specific and not suitable for detection Level 2 support in any other browser than Firefox.
