### ISSUE TITLE
H.264 and MP4 removal, since Chrome has ditched it, too

### ISSUE THREAD

**Issue by ghost** [WebPlatformTest/HTML5test#64]
http://blog.chromium.org/2011/01/html-video-codec-support-in-chrome.html

The only browser that will natively support MP4 is IE9. Since there is a consensus between everyone, except Microsoft, that MP4 should not be of the web, and that WebM should be, instead. I ask you to remove the part of the test that tests for MPEG-LA's codecs and containers.

Thanks!

**Comment by NielsLeenheer** [comment]
Way too early to remove H.264. There are currently still three shipping desktop browsers and even after a WebM only version of Chrome ships, both Safari and IE are still supporting H.264. Safari and IE have more than 50% market share. The video format wars are a long way from over, so it is appropriate from testing for both.

**Comment by ghost** [comment]
So is the goal of this to go with what is supported? IE9 will have H.264 for <video>; that won't get the 50% base, it will get much less than that; probably bringing to 1/4th.
The W3C does not consider H.264 open, and so they are against its use, the W3C is the creator of HTML5; respect them and drop testing support for H.264.

**Comment by NielsLeenheer** [comment]
The HTML5 working group has not chosen one of the two codecs as a minimum requirement and uses several examples of the H.264 codec in the specification. 

It is inappropriate to consider dropping H.264 until the W3C has actually chosen WebM as their baseline codec. And even if that happens it may be inappropriate to drop H.264, because I doubt the W3C will make WebM the only allowed codec for the video element.

**Comment by ghost** [comment]
"The HTML5 working group has not chosen one of the two codecs as a minimum requirement and uses several examples of the H.264 codec in the specification."
I know, but they heavily discourage its type.
"It is inappropriate to consider dropping H.264 until the W3C has actually chosen WebM as their baseline codec."
They don't need to, they already recommend against it.

**Comment by NielsLeenheer** [comment]
There is a difference between the personal opinions of one or more members of the HTML5 working group and official specifications released by the working group. The only way for the working group to recommend the use of one codec is to put it in the specification. The text of the specification is pretty clear. There is no preference or baseline codec for the HTML5 video element.

**Comment by ghost** [comment]
"There is a difference between the personal opinions of one or more members of the HTML5 working group and official specifications released by the working group."
I know, I am not saying they recommend against H.264 specifically; I am aware that the spec does not say no to it, either. The W3C is against the patents, which H.264 has many of, and so the W3C is against H.264; but they don't talk about it specifically in the HTML5 spec.

**Comment by glococo** [comment]
Well, its really funny to see a browser winning points because it use a corpocryme closed propietary codec, and pushing opensource browser to pay licences. In other words, html5test site is ALSO pushing Mozilla to pay licences and score a little higher.

If we see this... what more things was hidden in these tests to give some scoreUps in some browsers ?
How can we trust in this test ??

This test make me laugh.

**Comment by glococo** [comment]
BTW, Maybe will be better also to give some thumbs up to Silverlight, Java, Flash plugins ?¿¿
</ironic>

Again, So.. why you give points to h264 ?
Maybe because you think almost hardware decoders still not support VP8 ?(thats true)
but this conclusion became you think that h264 is the html5 standard ? 
Thinking in this way make Flash a standard plugin, and of course, should no be included in any browser by default. I think in the same way as h264.

cheers

**Comment by NielsLeenheer** [comment]
HTML5 does not specify a default codec. VP8 and H.264 are both equally
valid from a technical point of view. The politics are not something
we take into account for determining the score and not should it. We
just show what is supported.

BTW, Chrome did not drop support for H.264. And Firefox Mobile already
is or is going to support H.264 very soon.

On 30 jun. 2012, at 14:49, glococo
reply@reply.github.com
wrote:
